server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service

message: "Se levanta el microservicio catalog service"

#CONFIGURACIÓN DE EUREKA EN EL MICROSERVICIO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5

    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  
    instance:
      #hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      refer-ip-address: true
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10
  
  # CONFIGURACIÓN CORRESPONDENTE A LA IMPLEMENTACIÓN DE FEIGN
  feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  # EVALUAR SUMAR DEPENDENCIA PARA MEJORAR PREFORMANCE / Tolerancia a fallos
  #hystrix:
    #enabled: true

# SUMO LOGGING PARA VER CUALQUIER PROBLEMA RELATIVO AL BALANCEO
  logging:
  level:
    com.netflix.loadbalancer: DEBUG
  


    