server:
  port: ${PORT: ${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service

message: "Se levanta el microservicio catalog service"

#CONFIGURACIÓN DE EUREKA EN EL MICROSERVICIO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5

    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  
    instance:
      preferer-ip-address: true
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10
  
  # CONFIGURACIÓN CORRESPONDENTE A LA IMPLEMENTACIÓN DE FEIGN
  feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true

    