server:
  port: ${PORT:$(SERVER_PORT:8083)}}

spring:
  application:
    name: gateway
    cloud:
      gateway:
      locator:
        enabled: true
      routes:
        -id: id-catalog-service
        uri: lb://catalog-service
        predicates:
          -Path=/api/v1/catalog/**

info:
  application:
    name: ${spring.application.name}
    description: API Gateway para aplicacion
    version: 1.0.0

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  instance:
    #hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka

    
    
